name 'chef-unl-os'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-unl-os'
long_description 'Installs/Configures chef-unl-os'
version '0.1.0'
