name 'neutron'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures neutron'
long_description 'Installs/Configures neutron'
version '0.1.0'
