name 'packstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_unl_packstack'
long_description 'Installs/Configures chef_unl_packstack'
version '0.1.0'
